version: '3.4'

services:
  dockermicroservices.firstapi:
    image: ${DOCKER_REGISTRY-}dockermicroservicesfirstapi
    build:
      context: .
      dockerfile: src/DockerMicroservices.FirstApi/Dockerfile

  dockermicroservices.secondapi:
    image: ${DOCKER_REGISTRY-}dockermicroservicessecondapi
    build:
      context: .
      dockerfile: src/DockerMicroservices.SecondApi/Dockerfile

