version: '3.8'
services:
  first-api: # cannot contain uppercase chars
    build:
      context: .
      dockerfile: src/DockerMicroservices.FirstApi/Dockerfile
  second-api:
    build:
      context: .
      dockerfile: src/DockerMicroservices.SecondApi/Dockerfile
