# HTTPS configuration not done yet...
version: '3.8'
services:
  first-api:
    ports:
     - "44310:80" # for HTTP
    # - "44311:443" # for HTTPS
    #environment:
    # - ASPNETCORE_ENVIRONMENT=Development
    # - ASPNETCORE_URLS=https://+:443;http://+:80
    # - ASPNETCORE_Kestrel__Certificates__Default__Password=yourPasswordHere
    # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    #volumes:
    # - ~/.aspnet/https:/https:ro
  second-api:
    ports:
      - "54310:80"
      #- "54311:443"
