version: '3.4'

services:
  dockermicroservices.firstapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "44310:80"
      - "44311:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro # used for https stuff
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro # also for https
      - ~/docker_microservices/db:/app/host_db # the directory mounted from host
  dockermicroservices.secondapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "54310:80"
      - "54311:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - /app/container_db
      - ~/docker_microservices/db:/app/host_db:ro # same as in firstapi, only here it's readonly
